name: Release new version

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Chckout repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Get version number
        id: get-version
        run: node ./.github/scripts/get-version.js

      - name: Test
        run: |
          echo "Your version is"
          echo ${{steps.get-version.outputs.version }}
