name: Release new version

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Package and Release
    runs-on: ubuntu-latest
    steps:
      - name: Chckout repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Get version number
        id: get-version
        run: node ./.github/scripts/get-version.js

      - name: Zip files
        run: zip -r ./module.zip ./src/*

      - name: Create release
        run: gh release create ${{steps.get-version.outputs.version}} ./src/module.json ./module.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
